<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome to QTrip_autocomplete</name>
   <tag></tag>
   <elementGuidId>1511eb88-168d-4466-8290-2b1f325b69bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#autocomplete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='autocomplete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36b15afc-bba5-4ec8-8221-35a4b099c477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hero-input</value>
      <webElementGuid>8f15b087-747d-4514-9054-c29aa73a039a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autocomplete</value>
      <webElementGuid>ca463daa-40cb-4bd7-8f0a-0b252dba3f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search a City </value>
      <webElementGuid>e72971fb-a076-40f9-ad64-99c3bcf6bed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autocomplete&quot;)</value>
      <webElementGuid>582d4ab9-9a40-432d-a94f-099e58798457</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='autocomplete']</value>
      <webElementGuid>6a176176-6559-4c4a-b55b-e55922ef6f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fd399973-27ab-4b4f-8d3a-396c0d58f393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'autocomplete' and @placeholder = 'Search a City ']</value>
      <webElementGuid>da220618-2435-4eeb-9895-7d47afcbafe2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
