<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address_password</name>
   <tag></tag>
   <elementGuidId>aa2ad339-0fe4-42fd-89e4-37329445e47f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#floatingPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floatingPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7c2560c-d5e3-4bd4-b54a-318a27684ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f34dda89-2770-47b1-9fda-a3cc79df19f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ccf0a4f8-f3c3-4e6a-a67e-4a89b66a8ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7a5a8424-d560-471c-bff5-aec40e527aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floatingPassword</value>
      <webElementGuid>36111aa3-7357-447a-b74c-5b44eff36ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type to create account password</value>
      <webElementGuid>225b5523-b90c-43d6-820f-2ed48ae217bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerForm&quot;)/div[@class=&quot;form-floating mb-3&quot;]/input[@id=&quot;floatingPassword&quot;]</value>
      <webElementGuid>1fdd084f-6166-4503-add9-2ab88c2664e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floatingPassword']</value>
      <webElementGuid>c1ceae8c-a2ab-48a7-a4ee-a258a02447dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div[2]/input</value>
      <webElementGuid>7f1ba55a-42d5-4f62-bd8c-62e0b28412ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>7c0b9306-4c06-4006-a431-fc9a3e73e93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @id = 'floatingPassword' and @placeholder = 'Type to create account password']</value>
      <webElementGuid>6106849d-a933-4465-b5d8-c5dd8b8b094f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
