<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Paris</name>
   <tag></tag>
   <elementGuidId>030fd2e8-309b-424b-8901-4aa1ac94896e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paris > #paris</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='paris']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8a1d13ae-fa5d-46a8-aff0-078e1ff11ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paris</value>
      <webElementGuid>86d6bac3-3556-4faa-b287-b238d9eaaacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Paris </value>
      <webElementGuid>7df50358-98cd-40b6-9d46-a173f4a78a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;results&quot;)/a[@id=&quot;paris&quot;]/li[@id=&quot;paris&quot;]</value>
      <webElementGuid>336699e6-5513-409f-9d88-c488eff2d7cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='paris']</value>
      <webElementGuid>db44d688-540a-44be-80dd-0f433b024eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='paris']/li</value>
      <webElementGuid>4fd0bc49-d206-4be2-9d55-bc84bc11ba09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to QTrip'])[1]/following::li[1]</value>
      <webElementGuid>10467a7d-6ad7-40d2-be4f-7df503a4c164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::li[1]</value>
      <webElementGuid>c38a09c9-357e-45a2-ba0d-2f14ea0c48a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bengaluru'])[1]/preceding::li[1]</value>
      <webElementGuid>0eb7b89c-4b9b-4a3a-be1a-00908b20fa09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Goa'])[1]/preceding::li[1]</value>
      <webElementGuid>3d0403f0-4557-4257-81bd-e115da2b8b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Paris']/parent::*</value>
      <webElementGuid>dd37bf57-c58e-4323-9521-4661d101c9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/li</value>
      <webElementGuid>6ec905ce-aff4-4b65-9e0d-74d56cb25fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'paris' and (text() = ' Paris ' or . = ' Paris ')]</value>
      <webElementGuid>070bbc49-82e4-4478-abef-677de0518d57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
