<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>4bf2d4b3-9d42-41af-87cb-8064ba451466</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reservation-table > tr > td:nth-of-type(8) > #35e3e64cc79022ad > #35e3e64cc79022ad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='35e3e64cc79022ad']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>93a447e0-9f27-4a7b-b6c4-ad5922ca352b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>35e3e64cc79022ad</value>
      <webElementGuid>dc6ba507-7717-4b8d-a88f-b07258f92ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cancel-button</value>
      <webElementGuid>9940ed13-4b6c-4c25-9556-36c70b2e2a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>cancelReservation(this)</value>
      <webElementGuid>b4de12f4-ecad-4cd9-87f4-fd38755aff4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>8ec6c0d3-50b4-4639-94a0-c6e4b4647a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reservation-table&quot;)/tr[1]/td[8]/div[@id=&quot;35e3e64cc79022ad&quot;]/button[@id=&quot;35e3e64cc79022ad&quot;]</value>
      <webElementGuid>cedd7930-f51a-4e53-8de8-52c908322e44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='35e3e64cc79022ad']</value>
      <webElementGuid>85679663-161a-42e5-a309-33ed70ec16c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='35e3e64cc79022ad']/button</value>
      <webElementGuid>ff487789-6c85-4dbc-b786-b3fa317689ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit Adventure'])[1]/following::button[1]</value>
      <webElementGuid>90de9233-2cd6-47ff-8ef2-55509af5744d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ulgreen Upon Pockporth'])[1]/following::button[1]</value>
      <webElementGuid>2b165643-b418-4bd9-a19c-93cc1a37d564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© QTrip 2020'])[1]/preceding::button[1]</value>
      <webElementGuid>9f7f6f52-9c30-40b8-b96e-3f42fc88c6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>cff07acd-d7d0-47ce-9df2-6b95293f66e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '35e3e64cc79022ad' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>d9a15e60-a29b-40f3-9fb5-9240d80d1f89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
