<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Logout</name>
   <tag></tag>
   <elementGuidId>2c13f686-9723-48f2-a1f3-30a699fca834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.nav-link.login.register</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='Logout()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5938ee2f-84e5-4e9c-a107-7ad5cda95675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link login register</value>
      <webElementGuid>fd70f2d5-6b23-41b8-9cdd-7ec02124c195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Logout()</value>
      <webElementGuid>5e162692-455c-4552-a974-50ac1dfd7a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>fbd64c9d-e389-4a0f-9f0f-b2a812a5ea4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarNavDropdown&quot;)/ul[@class=&quot;navbar-nav d-flex justify-content-end w-100&quot;]/li[@class=&quot;nav-item auth&quot;]/div[@class=&quot;nav-link login register&quot;]</value>
      <webElementGuid>0e98cdcf-6263-46a9-98e3-aa301fc6dfc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='Logout()']</value>
      <webElementGuid>8bb64c19-58d8-475c-8944-75c67dc7447b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarNavDropdown']/ul/li[3]/div</value>
      <webElementGuid>7e4f153b-af78-4911-8423-372e44e41b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::div[1]</value>
      <webElementGuid>e899879e-eb15-40ab-ab54-ce56f34f6adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QTrip'])[1]/following::div[2]</value>
      <webElementGuid>b5faa886-695e-44b7-ab7c-888f9e51365b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Reservations'])[1]/preceding::div[1]</value>
      <webElementGuid>2f9cb2e7-9a2c-4f78-99e6-70fcc7eda843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>ada23fc4-7922-4b40-8269-d3cacb5d0486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div</value>
      <webElementGuid>60d01822-203c-40de-b388-c2050b390ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>8735147f-de01-4d1d-b4cc-2e4df734aab4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
