<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Party_img-responsive</name>
   <tag></tag>
   <elementGuidId>5f42dc40-0997-4903-81e4-99c719e49798</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#6905241907 > div.activity-card > img.img-responsive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='6905241907']/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c824034e-733c-4fe4-a78b-bc08ad8bee21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>86da7d6d-8e71-4623-9fa2-7a2674b22950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.pexels.com/photos/570032/pexels-photo-570032.jpeg?auto=compress&amp;cs=tinysrgb&amp;h=650&amp;w=940</value>
      <webElementGuid>161d6c31-c818-4cd1-a608-eb2bb5376efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6905241907&quot;)/div[@class=&quot;activity-card&quot;]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>f011f945-2c20-4ed3-892c-023704db06b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='6905241907']/div[2]/img</value>
      <webElementGuid>fc3efad9-7e28-4aa6-93b5-0559eca4a2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://images.pexels.com/photos/570032/pexels-photo-570032.jpeg?auto=compress&amp;cs=tinysrgb&amp;h=650&amp;w=940')]</value>
      <webElementGuid>1a9248dd-e6fd-4343-b29d-8b7f0ac9d180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div[2]/img</value>
      <webElementGuid>c0a68e3f-83b6-43dd-b402-180b1a2561bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://images.pexels.com/photos/570032/pexels-photo-570032.jpeg?auto=compress&amp;cs=tinysrgb&amp;h=650&amp;w=940']</value>
      <webElementGuid>9ad71c2b-135f-49d5-b61c-cecd5b6cc0f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
