<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pick a Date_date</name>
   <tag></tag>
   <elementGuidId>9de3c4c7-df57-44f6-80c7-cae98f15b67d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;myForm&quot;]/input[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;date&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7c01715-f03f-4b66-8307-6df919111efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>825f48d7-184a-42b5-86bb-4aad9afd11bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c3a8fcc6-d8bd-4e30-bd7a-fb5860684559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>72abcbf4-9fcc-4540-b06f-12849752ccd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myForm&quot;)/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>4ae31fd0-c9cb-48ae-8792-4a1d6f2ae81a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='date']</value>
      <webElementGuid>6e194a2e-0c3f-41dd-b76a-231508dc6504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='myForm']/input[2]</value>
      <webElementGuid>cbea7ec5-cb0a-4c33-a52f-ae94cac85626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>e6b40bee-27a3-4dcc-a43f-87eefc250ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'date']</value>
      <webElementGuid>74a93e0c-6394-44c7-9172-2da27eda964a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
