<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_35e3e64cc79022ad</name>
   <tag></tag>
   <elementGuidId>bdbeddca-3a28-4499-a48c-4658f392eabb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reservation-table > tr > th</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='reservation-table']/tr/th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>9394c934-b966-48f2-96f2-97cb1beeaa9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>25238638-b7c4-48b9-8f36-35518e5e05d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>35e3e64cc79022ad</value>
      <webElementGuid>bdc8ee83-ac6f-4ae3-bdc4-f4d09a54a03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reservation-table&quot;)/tr[1]/th[1]</value>
      <webElementGuid>89b671dc-c753-4fe5-9dcf-bee7342fa54a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='reservation-table']/tr/th</value>
      <webElementGuid>de01664a-bc4b-44c6-9540-f741a30c113e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::th[1]</value>
      <webElementGuid>d3aa7f77-fd48-41bb-a65b-64050858041b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::th[2]</value>
      <webElementGuid>2c92f92e-b7a2-4a73-ab0e-1292989cbba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nika'])[1]/preceding::th[1]</value>
      <webElementGuid>69ff8fbd-1f6a-4d92-b1ef-d9dfa8908740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ulgreen Upon Pockporth'])[1]/preceding::th[1]</value>
      <webElementGuid>d05e89b5-9c47-4ab2-a75b-498009b16a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='35e3e64cc79022ad']/parent::*</value>
      <webElementGuid>0e05e0c7-5006-4776-aa4b-e2426dfb910e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/th</value>
      <webElementGuid>ed3d152a-c87e-430b-af7f-462c54424ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = '35e3e64cc79022ad' or . = '35e3e64cc79022ad')]</value>
      <webElementGuid>a3b03193-332e-43ad-8471-f0a520c90b84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
