<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Clear</name>
   <tag></tag>
   <elementGuidId>1303c771-8997-429a-93f3-c4ccccdb39a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='resetAdventuresData()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>67e3cce2-bc67-482b-9ec5-4904553365b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-3</value>
      <webElementGuid>18708fea-ee47-4034-baef-a9c515e81e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>resetAdventuresData()</value>
      <webElementGuid>99816add-76b8-4996-a979-b3ed420dd800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Clear
              </value>
      <webElementGuid>a80dfb8b-07a0-44a2-8873-79b124b51942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;mb-5&quot;]/div[@class=&quot;filter-bar d-flex align-items-center&quot;]/div[@class=&quot;filter-bar-tile d-flex align-items-center&quot;]/div[@class=&quot;ms-3&quot;]</value>
      <webElementGuid>f247a7d0-d597-4204-8d7b-cac1bc288679</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='resetAdventuresData()']</value>
      <webElementGuid>2a3188ca-46b8-4d55-8120-d56a7b8080d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[2]/following::div[2]</value>
      <webElementGuid>cbd01cd3-9516-4c81-927a-0b00a3e00cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/following::div[4]</value>
      <webElementGuid>ceefe3bf-0e13-40a1-99c8-fa7f689cbfbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cycling'])[1]/preceding::div[1]</value>
      <webElementGuid>b970753e-1ba9-4184-9913-97805f1d395c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cycling'])[2]/preceding::div[5]</value>
      <webElementGuid>040115d8-7d3b-42ad-9129-a499e71d4e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>e4021abf-e88f-4087-bc1b-699cdcde9741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                Clear
              ' or . = '
                Clear
              ')]</value>
      <webElementGuid>ccc7ab94-2c14-4a99-8722-a7fa4bbc5316</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
