<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome to QTrip_autocomplete</name>
   <tag></tag>
   <elementGuidId>d2877e81-53c5-4cdb-a0ca-c1cb5f34f52c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#autocomplete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='autocomplete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46a0dbe2-ad12-4dd5-9b71-6dbddca776c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hero-input</value>
      <webElementGuid>bd0e2f1e-ba0f-47f1-9570-6cbb8b126c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autocomplete</value>
      <webElementGuid>f9cccf6a-1ccb-449c-80b1-5955b014d4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search a City </value>
      <webElementGuid>dbc45a01-edbe-4b6f-898c-29e948c40a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autocomplete&quot;)</value>
      <webElementGuid>9bc5dcb2-38ea-4e40-ab48-44a16574fb9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='autocomplete']</value>
      <webElementGuid>b614c402-96e4-4416-8dad-27e89bee9466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0eeb3a58-6038-4cfa-807d-19b0d85b9f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'autocomplete' and @placeholder = 'Search a City ']</value>
      <webElementGuid>9a8f6d4c-3940-45f7-8c82-9bf2d49f2179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
