<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Goa</name>
   <tag></tag>
   <elementGuidId>caa0ee42-6f55-4aa1-8145-a3f215fe47ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#goa > #goa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='goa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>00967ae8-b30b-4025-a0bf-b0059af7d10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>goa</value>
      <webElementGuid>f104c39c-3809-4487-85af-09a33aed280e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Goa </value>
      <webElementGuid>ac129da1-3b06-431b-8c3e-5d7e032586f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;results&quot;)/a[@id=&quot;goa&quot;]/li[@id=&quot;goa&quot;]</value>
      <webElementGuid>ddb4741a-bb90-48b6-a811-b43c2c867278</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='goa']</value>
      <webElementGuid>356246ee-3440-4204-a29b-202bd1a21de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='goa']/li</value>
      <webElementGuid>7f606ef8-65ec-4a79-a3dd-9d7286f7cdfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to QTrip'])[1]/following::li[1]</value>
      <webElementGuid>9afa010a-6c7c-44ab-a3b4-8b4a2a13beee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::li[1]</value>
      <webElementGuid>2c28e798-1e14-4246-a1da-9ea3bbecfba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bengaluru'])[1]/preceding::li[1]</value>
      <webElementGuid>b3ca8ff9-341c-4195-a4d3-a5c994136ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Goa'])[2]/preceding::li[1]</value>
      <webElementGuid>340b2366-d119-48cc-813a-6134bfc304ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Goa']/parent::*</value>
      <webElementGuid>3715aa92-8e94-4c27-a331-17720cc91a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/li</value>
      <webElementGuid>d3a8b8c9-d6c5-4c01-a50e-f85ab67388f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'goa' and (text() = ' Goa ' or . = ' Goa ')]</value>
      <webElementGuid>58c9ebdc-716b-492d-9285-2738c551e53e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
