<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Register_email</name>
   <tag></tag>
   <elementGuidId>9df98e8a-7be1-42dc-a69b-a45b5504f5e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#floatingInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floatingInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05da6cfd-4e32-43df-baf6-93db740c9776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f6f99c25-2518-439f-a5f7-cd6d47d5baa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>48e1fa91-6e08-46a1-b22a-d340367ec0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3a4cfaa0-f7a0-424d-97e7-6e25b6e76694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floatingInput</value>
      <webElementGuid>f5a9fb8f-4bf9-45d7-9c7e-429f407a834b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>name@example.com</value>
      <webElementGuid>e33373ff-a878-44d9-9a8b-19323dd88e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floatingInput&quot;)</value>
      <webElementGuid>c05d0931-c6cc-4b03-a619-0fea5e85ad23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floatingInput']</value>
      <webElementGuid>aedc01ca-f7cd-42b0-8bae-72084449ce06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div/input</value>
      <webElementGuid>1e50e6ae-b850-4ead-9e5e-3854af1c8367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0fcaa9df-dbf7-4bb1-ac16-f7003df78f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email' and @id = 'floatingInput' and @placeholder = 'name@example.com']</value>
      <webElementGuid>99668d05-6b94-495d-9203-567639c28676</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
